server:
  port: 8000

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    #是否从Eureka抓取已有的注册信息，默认true。集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#feign客户端超时时间（feign默认支持ribbon）
ribbon:
  #建立连接所用时间
  ConnectTimeout: 5000
  #建立连接后从服务器读取到可用资源的时间
  ReadTimeout: 5000

logging:
  level:
    #fegin日志以什么级别监控那个接口
    com.learn.cloud.service.PaymentFeignService: debug