server:
  port: 3344

spring:
  application:
    name: cloud-server-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:bloomL/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
          # 读取分支
          default-label: master

eureka:
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka
