server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  #eureka服务端实例名称
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      # 单机版 defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/