server:
  port: 8006
spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: 47.111.250.196
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        #ip-address: 192.168.1.3
