server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
          #路由id，无固定规则但要求唯一
        - id: payment_route
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #动态路由
          uri: lb://CLOUD-PAYMENT-SERVICE
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/pay/**
            - After=2020-09-16T21:20:57.505+08:00[Asia/Shanghai]
            #- Before=2020-09-16T21:20:57.505+08:00[Asia/Shanghai]
            #- Between=2020-09-16T21:20:57.505+08:00[Asia/Shanghai],2020-09-26T21:20:57.505+08:00[Asia/Shanghai]
            #- Cookie=username,lg
            # 请求头有X-Request-Id属性且值为整数
            #- Header=X-Request-Id,\d+
            #- Method=GET
            # 参数名要有username且为整数  eg:xxx?username=12
            #- Query=username,\d+

eureka:
  client:
    #在Eureka注册中注册服务
    register-with-eureka: true
    #是否从Eureka抓取已有的注册信息
    fetch-registry: true
    service-url:
      #单机 注册中心地址
      defaultZone: http://localhost:7001/eureka
