server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端实例名称
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/
      # 集群 defaultZone: http://eureka7002.com:7002/eureka/
  #关闭自我保护
  #server:
   # enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000