server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #需绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.111.250.196
                port: 5672
                username: guest
                password: guest
      bindings: #服务整合处理
        input:
          destination: studyExchange  #要使用的Exchange的名称
          content-type: application/json
          default-binder: defaultRabbit
          group: study #同一组，存在竞争，只有一个能消费，避免重复消费

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳时间间隔（默认30s）
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802.com  #信息列表显示的主机名称
    prefer-ip-address: true     #访问路径变为IP
