server:
  port: 8004

#服务别名，注册到zookeeper注册中心名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: 47.111.250.196:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.learn.cloud.entity    #所有entity别名类所在的包